### ISSUE TITLE
Issues in Lab

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#11]
Please find the issues mentioned below
Hands on Lab:- 
1.  **Exercise 1: Using data virtualization** > Task 1: Create external table from Azure SQL Database.
I am not able to run the query in Azure Data Studio and i tried using SSMS also but faced same issue. 

Below is the error i am getting while running the querry:- 

**Msg 110045, Level 16, State 1, Line 52
110045;User authorization failed: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'admin'. Additional error <2>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'admin'., SqlState: 28000, NativeError: 18456** 

![image](https://user-images.githubusercontent.com/45102602/72979482-6a24b700-3dfe-11ea-92e3-0b4b017d934f.png)

2.   **Exercise 1: Using data virtualization** > Task 2: Create external table from CSV files
  I am not getting the **Create External Table From CSV Files** option. Can you please let me know that which version of Azure Data Studio you are using for the workshop.

![image](https://user-images.githubusercontent.com/45102602/72979608-b8d25100-3dfe-11ea-9c10-959ff9236e09.png)

**Comment by akn9050** [comment]
Hi Tim, 

Any update on this so far.


Thanks,
Amit

**Comment by feaselkl** [comment]
Hi @sumitmalik51 .

For your first question, the error message indicates that you're using the **admin** login.  If you've been following the workshop, the Azure SQL Database administrative account is called **ServerAdmin**.  You can certainly use different credentials from what is in the workshop, but please double-check that your login and password are correct.

For your second question, the screenshots came from a recent post-SQL Server 2019 release of Azure Data Studio with the [Data Virtualization extension](https://docs.microsoft.com/en-us/sql/azure-data-studio/data-virtualization-extension?view=sql-server-ver15) installed; I believe it was the November release.  Could you double-check to make sure you have the Data Virtualization extension installed and up to date?  The latest version of that extension is 1.2.0.

**Comment by sumitmalik51** [comment]
Hi @feaselkl .
Yes i am sure i am using correct credentials for Azure SQL, Also i am able to login to the database with the same credentials.

Thanks,
Sumit

**Comment by timahenning** [comment]
@sumitmalik51 Sumit - did you check the Data Virtual extension?

**Comment by feaselkl** [comment]
Hi, @sumitmalik51 

I ran through the [before-the-lab process](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Modernizing%20Data%20Analytics%20with%20SQL%20Server%202019.md) tonight and didn't experience any problems with the exercise.  I'm thinking that the issue is related to your database scoped credential.  I'd recommend dropping the pieces and trying again.  Here is a script that would do this:

```
IF (OBJECT_ID('dbo.Reviews') IS NOT NULL)
    DROP EXTERNAL TABLE dbo.Reviews;
IF EXISTS (SELECT * FROM sys.external_data_sources WHERE name = N'SQLServerInstance')
    DROP EXTERNAL DATA SOURCE SQLServerInstance;
IF EXISTS (SELECT * FROM sys.database_scoped_credentials WHERE name = N'SQLCred')
    DROP DATABASE SCOPED CREDENTIAL SQLCred;
```

Then, double-check that the database scoped credential creation statement is correct, that it's your Azure SQL Database credentials.  Here's the relevant part of that script:

```
IF NOT EXISTS
(
  SELECT 1
  FROM sys.database_scoped_credentials
  WHERE
    name = N'SQLCred'
)
BEGIN
  -- specify credentials to external data source
  -- IDENTITY: user name for external source.
  -- SECRET: password for external source.

  CREATE DATABASE SCOPED CREDENTIAL SQLCred
  WITH IDENTITY = 'ServerAdmin',
  SECRET = 'MySQLBigData2019';
END
GO
```

One other thing to try is to make sure that your Azure SQL Database can connect to other Azure services.  The easy route (which we show in the lab) is to select the "Allow access to Azure services" toggle on your Azure SQL Database's firewall settings.  That's a less likely cause but I wanted to throw that out just in case.

**Comment by timahenning** [comment]
We have not heard any feedback from the field.  We will be happy to open the issue if needed.
