### ISSUE TITLE
Resource Deployment Failure - Code: Conflict

### ISSUE THREAD

**Issue by kinghendrix10** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#18]
Tried using the specified template - [https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/template.json](url) but deployment keeps failing 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"NameAlreadyExists\",\r\n \"message\": \"The name 'init-sql-mod-data.database.windows.net' already exists. Choose a different name.\"\r\n }\r\n ]\r\n }\r\n}"}]}

Tried figuring out myself but nothing I've tried has worked so far. Some help would go a long way.

Thanks

**Comment by kinghendrix10** [comment]
Thanks

**Comment by feaselkl** [comment]
There is already a SQL Server instance provisioned in your region named **init-sql-mod-data.database.windows.net**.  The fix is to change the **Sqlservername** parameter in the deployment template from **INIT-sql-mod-data** to use your initials or some other prefix which makes your server name unique.

![image](https://user-images.githubusercontent.com/1330589/93130463-90a2a580-f6a0-11ea-9219-a21cc5d995ec.png)

**Comment by kinghendrix10** [comment]
I tried that... But I think because I am using preset parameters from the template.json file as specified for the tutorial. Changing the Sqlservername parameter ended up giving another error (null database or something like that). Tried changing regions but the errors still continued

**Comment by feaselkl** [comment]
Could you try deleting the resource group you created for this, re-create the resource group, and try again changing the SQL Server name to ###-sql-mod-data, where ### is some unique value?  I was able to deploy with **klf** as the initials; you can even try using that server name, as I've deleted the resource group I created so that server name is available again.

![image](https://user-images.githubusercontent.com/1330589/93155843-f90b7a00-f6d4-11ea-8d84-c94c86b71589.png)

If you get an error doing that, please post the error and we can investigate further.

**Comment by kinghendrix10** [comment]
Okay got it fixed, I had to edit the SQL server name field as suggested but that still gave another error till I also did the same on the editor as well. Thanks
