### ISSUE TITLE
Error while Restoring sales database to Big Data cluster

### ISSUE THREAD

**Issue by Grv-Singh** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#19]
In Task 4 : Step 3, before HOL

Output of `kubectl get svc -n mssql-cluster` from Azure-cli reveales for TCP connection ⤵

![image](https://user-images.githubusercontent.com/12825441/93438792-68f34d80-f8eb-11ea-89e1-3b8fe5cae6fb.png)

- KNOX_PORT = 32722

![image](https://user-images.githubusercontent.com/12825441/93438924-8de7c080-f8eb-11ea-98a3-29a0e1ea0ab9.png)

- SQL_MASTER_PORT = 32626

therefore the change is made [here](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/bootstrap-sample-db.cmd#L22) & [here ](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/bootstrap-sample-db.cmd#L23) and respective IPs are used.

On running `.\bootstrap-sample-db mssql-cluster x.y.w.z password c:/temp a.b.c.d --install-extra-samples` in command prompt.

.bak file gets downloaded in correct directory although,

probably because of [#44 in bootstrap-sampl-db.cmd](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/bootstrap-sample-db.cmd#L44) results into ⤵

**Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: The wait operation timed out.**

Please help solving this error 😞

**Comment by feaselkl** [comment]
If I am understanding correctly, you changed lines 22 and 23 of the `bootstrap-sample-db.cmd` script to use the container's internal ports (32722 for Knox and 32626 for SQL Server, respectively) instead of the external ports of 30443 and 31433.  You should **not** use those internal ports with the script--because you are connecting from outside the container, those ports are not exposed and available.  The KNOX_PORT should remain 30433 and SQL_MASTER_PORT 31433.

Here is a sample call.  Please note that the IP addresses are the **second** IP addresses in `kubectl`'s output--the first IP address for each service will likely be in the `10.0.x.x` range and will not be directly available to you.  In my case, suppose the external IP address for connection to SQL Server is 52.170.174.25 and the external IP address for Knox is 52.191.85.30.

`bootstrap-sample-db.cmd mssql-cluster 52.170.174.25 <password> 52.191.85.30 <password> --install-extra-samples`

Running the command like noted above and with the original ports specified in the script file, you should see results which look like the following:

![image](https://user-images.githubusercontent.com/1330589/93544433-12f2ca00-f92c-11ea-8247-45eee30a96a9.png)

Please let me know if this works for you; if it does not, we can troubleshoot further.

**Comment by Grv-Singh** [comment]
Thanks for all the guidance, I've carefully followed & replicated each step, although unfortunately - have encountered another error : 

![image](https://user-images.githubusercontent.com/12825441/93610612-e94ca800-f9ea-11ea-9691-820ce230d109.png)

I suspect default sqlcmd connection timeout of 8 seconds, even that didn't worked.

**Comment by feaselkl** [comment]
If you're getting errors downloading with curl, it sounds like a network issue.  Are you running these commands from the VM or from your local machine?  If the latter, it may be network issues and I'd recommend seeing if you can try to run the commands inside an RDP session to the VM.

If you are running the commands from your local machine, you might also need to check firewall settings for SQL Server to ensure that your client IP address is whitelisted; that can also lead to `Login timeout expired` errors when trying to connect to SQL Server.

One other thing to try is to get rid of the `c:/temp` reference in your call; neither my example above nor the instruction in Task 4, Step 3 requires an installation directory, leaving me to wonder if perhaps that parameter is being misinterpreted.

**Comment by timahenning** [comment]
@Grv-Singh Can we close this issue?

Tim

**Comment by Grv-Singh** [comment]
Apologies for a late response. Although, yes. This issue will be a closure.

**Comment by feaselkl** [comment]
Thank you for following up and let us know if you run into any other issues with the lab.
